from pathlib import Path

from IPython.display import SVG, display


def get_svg_file(model_name):
    """Helper function to find the dot-file generated by InferenceEngine
    for the model with the given name. If multiple candidate files are 
    found, the most recent one is returned (InferenceEngine appends
    the current date-time to the model name).
    """
    all_files = [f for f in Path('.').glob(f'{model_name}*.svg')]
    return str(sorted(all_files)[-1])

def plot_graph(model_name):
    graph_file = get_svg_file(model_name)
    display(SVG(filename=graph_file))
